### ISSUE TITLE
Timeline

### ISSUE THREAD

**Issue by pradesga** [pradesga/fgsby#4]
Mas @alvisani tolong url timeline dimasukin ke slider pertama
thanks

**Comment by alvisani** [comment]
Sudah saya buat request pull mas #5

**Comment by pradesga** [comment]
ok

**Comment by pradesga** [comment]
@alvisani query timeline e salah mas kudune `(SELECT id, nama, tgl, kota, kode, konfirm FROM register)
UNION
(SELECT id, nama, tglbayar, kota, kode, konfirm FROM register WHERE tglbayar != '')
ORDER BY tgl`

**Comment by alvisani** [comment]
Cek om #7
